name: Rightmove Scraper

on:
  schedule:
    # Run at 9 AM UTC daily
    - cron: '0 9 * * *'
  workflow_dispatch: # Allow manual trigger

concurrency:
  group: scrape
  cancel-in-progress: false

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run scraper
        run: python scrape_rightmove.py

      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit and push
        run: |
          git add rightmove-output/
          git commit -m "Update property listings and photos" || true
          git pull --rebase --autostash
          git push
